 /* Modelagem Básica - 
ENTIDADE = TABELA 
CAMPOS = ATRIBUTOS */

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
E-MAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDEREÇO - CARACTER(100)
SEXO - CARACTER(1)

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E 02 - AD ADM DE DADOS */
MODELAGEM CONCEITUAL - RASCUNHO
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */
MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO MODELAGEM FISICA */

/* CHAR NÃO VARIA DE TAMANHO, VARCHAR VARIA DE TAMANHO 
CHAR É MAIS RAPIDO, PORTANTO UTILIZAMOS QUUANTO TEMOS CERTEZA DA QUANTIDADE DE CARACTERES -
POR EXEMPLO, A SIGLA DE UMA UNIDADE FEDERATIVA DF, SP, RJ, MG, ETC.. */

/* ENUM: CONJUNTO ENUMERADO DE DADOS, OU SEJA, UM NÚMERO FIXO DE DADOS. É UTILIZADO QUANDO
QUEREMOS LIMITAR OS DADOS EM UMA COLUNA OBS: SÓ EXISTE NO MYSQL*/

/* FUNÇÕES DE AGREGAÇÃO: COUNT(*) - CONTA O NÚMERO DE RESGISTROS, GROUP BY - AGRUPA OS 
RESGISTROS POR CONDIÇÃO*/

/* FLOAT: OFERECE MAIOR PRECISÃO, QUANDO NECESSÁRIO FLOAT(TOTAL, VÍRGULA) 
INT: NÚMEROS INTEIROS; MÁXIMO 11 DIGITOS, QUANDO EXEDE ESSE MÁXIMO UTILIZADO CHAR OU VARCHAR
(TAMBÉM UTILIZADOS QUANDO NÃO HÁ A NECESSIDADE DE CÁLCULOS  */ 

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	CPF INT(11),
	EMAIL VARCHAR(30),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

USE EXEMPLO;
SHOW TABLES;

USE PROJETO;

/* DESCOBRINDO COMO É A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* SINTAXE BÁSICA DE INSERÇÃO - INSERT INTO ..... */
 
 /* FORMA 01 - OMITINTO AS COLUNAS */
 
 INSERT INTO CLIENTE VALUES('Luiz', 'M', 1234567891, 'LUIZ@GMAIL.COM', '61999619870', 'Lago Norte - Brasília');

 INSERT INTO CLIENTE VALUES('Eduardo', 'M', 9874563211, 'EDUARDO@GMAIL.COM', '61985456332', 'Cruzeiro - Brasília');
 
 INSERT INTO CLIENTE VALUES('Júlia', 'F', 1472583691, 'JULIA@GMAI.COM', '61932457868', 'Ceilândia - Brasília');
 
 INSERT INTO CLIENTE VALUES('Brenda', 'F', 1472583621, NULL, '61932457858', 'Ceilândia - Brasília');
 
 /* FORMA 02 - COLOCANDO A COLUNA */
 
 INSERT INTO CLIENTE(NOME, CPF, ENDERECO, TELEFONE, SEXO, EMAIL) VALUES('Ricardo', 357951961, 'Taguatinga - Brasília', '61741852357', 'M', 'RICARDO@GMAIL.COM');
 
 INSERT INTO CLIENTE(NOME, CPF, ENDERECO, TELEFONE, SEXO) VALUES('GILMAR', 357951961, 'Taguatinga - Brasília', '61741852357', 'M');
 
 /* FORMA 03 - INSERT COMPACTO - SOMENTE SQL */
 
 INSERT INTO CLIENTE VALUES('Clara', 'F', 123456789, 'CLARA@YAHO.COM', '61997845129', 'Sobradinho - Brasília'),
						('ANA', 'F', 321654987,'ANA@GLOBO.COM', '61987654321', 'Planaltina - Brasília');
						
/* O COMANDO SELECT */
/* SELEÇÃO, PROJEÇÃO E JUNÇÃO */
/* PROJEÇÃO: FILTRA POR COLUNA*/
SELECT NOW();

SELECT NOW() AS DATA_HORA;

SELECT NOW() AS DATA_HORA, 'LUIZ' AS ESTUDANTE;

/* ALIAS DE CONLUNAS */

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

/* SOMENTE PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* SELEÇÃO: FILTRA PELA LINHA */
/* SELECIONA AS LINHAS SOMENTE O VALOR CORRESPONDENTE,
SELECIONA UM SUBCONJUNTO */

SELECT NOME, CPF FROM CLIENTE WHERE SEXO = 'M';

/* CARACTERE CORINGA %*/

SELECT NOME, CPF, TELEFONE FROM CLIENTE WHERE ENDERECO LIKE 'Taguatinga%';

/* EXERCICIO */

CREATE TABLE LIVROS(
	NOME_DO_LIVRO VARCHAR(30),
	NOME_DO_AUTOR VARCHAR(30),
	SEXO_DO_AUTOR CHAR(9),
	NUMERO_DE_PAGINAS CHAR(3),
	NOME_DA_EDITORA VARCHAR(30),
	VALOR_DO_LIVRO FLOAT(3,2),
	ESTADO_DA_EDITORA CHAR(2),
	ANO_PUBLICACAO CHAR(4)
	);
	
INSERT INTO LIVROS(NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_DA_EDITORA, ANO_PUBLICACAO) 
					VALUES ('Cavaleiro Real', 'Anal Claudia', 'Feminino', '465', 'Atlas', 49.90, 'RJ', '2009'),
					('SQL para leigos', 'João Nunes', 'Masculino', '450', 'Addison', 98.00, 'SP', '2018'),
				    ('Receitas Caseiras', 'Celia Tavares', 'Feminino', '210','Atlas', 45.00, 'RJ', '2008'),
					('Pessoad Efetivas', 'Eduardo Santos', 'Masculino', '390', 'Beta', 78.99, 'RJ', '2018'),
					('Hábitos Saudáveis', 'Eduardo Santos', 'Masculino', '630', 'Beta', 150.98, 'RJ', '2019'),
					('A Casa Marrom', 'Hermes Macedo', 'Masculino', '250', 'Bubba', 60.00, 'MG', '2016'),
					('Estacio Querido', 'Geraldo Fracisco', 'Masculino', '310', 'Insignia', 100.00, 'ES', '2015'),
					('Pra sempre amigas', 'Leda Silva', 'Feminino', '510', 'Insignia', 78.98, 'ES', '2011'),
					('Copas Inesqueciveis', 'Marco Alcantra', 'Masculino', '200', 'Larson', 130.98, 'RS', '2018'),
					('O poder da mente', 'Clara Mafra', 'Feminino', '120', 'Continental', 56.58, 'RS', '2017');

 /* ALTERANDO O TIPO DE UMA COLUNA */				
ALTER TABLE livros MODIFY VALOR_DO_LIVRO FLOAT(6,2);

SELECT NOME_DO_LIVRO AS Título, NOME_DA_EDITORA AS Editora FROM livros;

SELECT NOME_DO_LIVRO AS Título, ESTADO_DA_EDITORA AS UF_Editora, SEXO_DO_AUTOR FROM livros WHERE SEXO_DO_AUTOR = 'Masculino';

SELECT NOME_DO_LIVRO AS Título, NUMERO_DE_PAGINAS AS Quantidade_de_páginas, SEXO_DO_AUTOR FROM livros WHERE SEXO_DO_AUTOR = 'Feminino';

SELECT NOME_DO_LIVRO AS Título, VALOR_DO_LIVRO AS Valor, ESTADO_DA_EDITORA AS UF_Editora FROM livros WHERE ESTADO_DA_EDITORA = 'SP';

/* TABELA VERDADE*/
SELECT * FROM livros WHERE SEXO_DO_AUTOR = 'Masculino' AND (ESTADO_DA_EDITORA = 'SP' OR ESTADO_DA_EDITORA = 'RJ');

UPDATE livros SET NOME_DO_LIVRO = 'Pessoa Efetivas' WHERE NOME_DO_LIVRO = 'Pessoad Efetivas';

STATUS;

select NOME, EMAIL, TELEFONE FROM cliente WHERE SEXO = 'F' AND ENDERECO LIKE 'Taguatinga%';

SELECT NOME, EMAIL, TELEFONE FROM cliente WHERE SEXO = 'M' OR ENDERECO LIKE '%Brasília';

SELECT NOME_DO_LIVRO, VALOR_DO_LIVRO FROM livros WHERE VALOR_DO_LIVRO > 100;

SELECT NOME_DO_LIVRO, VALOR_DO_LIVRO


 /* ALTERANDO O TIPO DE UMA COLUNA */
ALTER TABLE livros MODIFY NUMERO_DE_PAGINAS INT(4);

ALTER TABLE livros MODIFY ANO_PUBLICACAO INT(4); 

SELECT NOME_DO_LIVRO, VALOR_DO_LIVRE, NUMERO_DE_PAGINAS, ANO_PUBLICACAO FROM livros WHERE ANO_PUBLICACAO <= 2015 AND NUMERO_DE_PAGINAS >= 400;

/* COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LOGICOS */

/* SELECT COUNT(*) MOSTRA A QUANTIDADE DE REGISTROS EM UMA TABELA */

SELECT COUNT(*) FROM cliente;
SELECT COUNT(*) AS 'QUANTIDADE DE RESGISTROS DA TABELA CLIENTE' FROM cliente;

SELECT SEXO, COUNT(*) FROM cliente GROUP BY SEXO;

SELECT ENDERECO, COUNT(*) FROM cliente GROUP BY ENDERECO;

SELECT * FROM FUNCIONARIOS WHERE departamento = 'Roupas' OR departamento = 'Filmes';

SELECT departamento, COUNT(*) FROM funcionarios GROUP BY departamento ORDER BY 2;

SELECT EMAIL FROM FUNCIONARIOS WHERE (DEPARTAMENTO = 'Filmes' OR DEPARTAMENTO = 'Lar') AND SEXO = 'Feminino';

SELECT COUNT(*) FROM FUNCIONARIOS WHERE SEXO = 'Masculino' OR DEPARTAMENTO = 'Jardim';

SELECT COUNT(*) FROM FUNCIONARIOS WHERE SEXO = 'Masculino' OR DEPARTAMENTO = 'Jardim';

SELECT DEPARTAMENTO FROM FUNCIONARIOS GROUP BY SEXO;

SELECT CARGO, COUNT(*) FROM FUNCIONARIOS GROUP BY CARGO;

SELECT COUNT(DISTINCT CARGO) FROM FUNCIONARIOS;

SELECT SEXO, COUNT(*) FROM FUNCIONARIOS WHERE DEPARTAMENTO = 'Jardim' GROUP BY SEXO;

 SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;
 
 SELECT ENDERECO, COUNT(*) FROM CLIENTE GROUP BY ENDERECO;

/* FILTRANDO VALORES NULOS */
/* TRAZ TODAS AS LINHAS COM A COLUNA EMAIL SEM VALOR*/ 
SELECT * FROM CLIENTE WHERE EMAIL IS NULL;
/* TRAZ TODAS AS LINHAS COM VALOR NA COLUNA EMAIL*/ 
SELECT * FROM CLIENTE WHERE EMAIL IS NOT NULL; 

/* UPDATE UTILIZADA PARA MODIFICAR/ADICIONAR DADOS, UTILIZAR WHERE SEMPRE */
UPDATE CLIENTE SET EMAIL = 'BRENDA@GMAIL.COM' WHERE NOME = 'Brenda';

/* DELETE */

/* PRIMEIRO SEMPRE CONTAR O TOTAL DE REGISTROS */

SELECT COUNT(*) FROM CLIENTE;
-- TOTAL DE 8 REGISTROS

-- SUPONDO QUE QUERO DELETAR TODOS OS REGISTROS COM ENDERECO DE TAGUATINGA
 SELECT COUNT(*) FROM CLIENTE WHERE ENDERECO LIKE 'Taguatinga%'; 
 -- TOTAL DE REGISTROS COM O ENDERECO TAGUATINGA É 3
 
 DELETE FROM CLIENTE WHERE ENDERECO LIKE 'Taguatinga%';
 
 -- TOTAL DE RESGISTROS DEPOIS DO DELETE É 5
 
 INSERT INTO CLIENTE(SEXO, CPF, EMAIL, ENDERECO, NOME, TELEFONE) VALUES('F', 98745231, 'MARCELO@GMAIL.COM', 'Taguatinga - Brasília', 'MARCELO', '61798984879'),
 ('F', 789456124, 'MARCELA@GMAIL.COM', 'Taguatinga - Brasília', 'MARCELA', '6149846111');
 
 DELETE FROM CLIENTE WHERE NOME = 'MARCELO' AND SEXO = 'F';
 
 /* PARA CONFERIR SE ESTÁ DELETANDO O CORRETO É TROCAR DELETE POR SELECT */

 SELECT * FROM CLIENTE WHERE NOME = 'MARCELO' AND SEXO = 'F';
 
 /* GROUP BY É IGUAL A DIVIDIR */
  
  CREATE DATABASE COMERCIO;
  
  USE COMERCIO;
  
  CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(11) UNIQUE,
	NOME VARCHAR(50) NOT NULL,
	SEXO ENUM('M', 'F') NOT NULL
	);
  
  CREATE TABLE ENDERECO(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	ESTADO CHAR(2) NOT NULL,
	MUNICIPIO VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	RUA VARCHAR(30) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
	);
	
  CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO_TELEFONE ENUM('PESSOAL', 'RESIDENCIAL', 'COMERCIAL') NOT NULL,
	NUMERO VARCHAR(11) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
	);
	
	/* PRIMEIRA FORMA NORMAL */

/*

1 - TODO CAMPO VETORIZADO SE TORNAR'A OUTRA TABELA

[AMARELO, AZUL, LARANJA, VERDE] -> CORES
[KA, FIESTA, UNO, CIVIC]-> CARROS

2 - TODO CAMPO MULTIVALORADO SE TORNAR'A OUTRA TABELA.
QUANDO O CAMPO FOR DIVIS'IVEL

3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE IDENTIFIQUE
TODO O REGISTRO COMO SENDO UNICO.
ISSO ;E O QUE CHAMAMOS DE CHAVE PRIMARIA OU PRIMARY KEY.


*/

/* CADINALIDADE */

/* QUEM DEFINE A CARDINALIDADE É A REGRA DE NEGOCIOS */

/* PRIMEIRO ALGARISMO - OBRIGATORIEDADE 
0 - NAO OBRIGATORIO
1 - OBRIGATORIO

SEGUNDO ALGARISMO - CARDINALIDADE
1 - MAXIMO DE UM
N - MAIS DE UM
*/

INSERT INTO CLIENTE(IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'JOAO','M','JOAOA@IG.COM','76567587887');
INSERT INTO CLIENTE(IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE(IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE(IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE(IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE(IDCLIENTE, NOME, SEXO, EMAIL, CPF) VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');

+-----------+---------------+------+-----+---------+----------------+
| Field     | Type          | Null | Key | Default | Extra          |
+-----------+---------------+------+-----+---------+----------------+
| IDCLIENTE | int(11)       | NO   | PRI | NULL    | auto_increment |
| EMAIL     | varchar(50)   | YES  | UNI | NULL    |                |
| CPF       | varchar(11)   | YES  | UNI | NULL    |                |
| NOME      | varchar(50)   | NO   |     | NULL    |                |
| SEXO      | enum('M','F') | NO   |     | NULL    |                |
+-----------+---------------+------+-----+---------+----------------+


DROP TABLE CLIENTE;

INSERT INTO ENDERECO(IDCLIENTE, RUA, BAIRRO, MUNICIPIO, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA ANTONIO SA','CENTRO','B. HORIZONTE','MG',4);
INSERT INTO ENDERECO(IDCLIENTE, RUA, BAIRRO, MUNICIPIO, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA CAPITAO HERMES','CENTRO','RIO DE JANEIRO','RJ',1);
INSERT INTO ENDERECO(IDCLIENTE, RUA, BAIRRO, MUNICIPIO, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA PRES VARGAS','JARDINS','SAO PAULO','SP',3);
INSERT INTO ENDERECO(IDCLIENTE, RUA, BAIRRO, MUNICIPIO, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA ALFANDEGA','ESTACIO','RIO DE JANEIRO','RJ',2);
INSERT INTO ENDERECO(IDCLIENTE, RUA, BAIRRO, MUNICIPIO, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA DO OUVIDOR','FLAMENGO','RIO DE JANEIRO','RJ',6);
INSERT INTO ENDERECO(IDCLIENTE, RUA, BAIRRO, MUNICIPIO, ESTADO, ID_CLIENTE) VALUES(NULL,'RUA URUGUAIANA','CENTRO','VITORIA','ES',5);

INSERT INTO TELEFONE(IDTELEFONE, TIPO_TELEFONE, NUMERO, ID_CLIENTE) VALUES(NULL,'PESSOAL','78458743',5);
INSERT INTO TELEFONE(IDTELEFONE, TIPO_TELEFONE, NUMERO, ID_CLIENTE) VALUES(NULL,'RESIDENCIAL','56576876',5);
INSERT INTO TELEFONE(IDTELEFONE, TIPO_TELEFONE, NUMERO, ID_CLIENTE) VALUES(NULL,'PESSOAL','87866896',1);
INSERT INTO TELEFONE(IDTELEFONE, TIPO_TELEFONE, NUMERO, ID_CLIENTE) VALUES(NULL,'COMERCIAL','54768899',2);
INSERT INTO TELEFONE(IDTELEFONE, TIPO_TELEFONE, NUMERO, ID_CLIENTE) VALUES(NULL,'RESIDENCIAL','99667587',1);
INSERT INTO TELEFONE(IDTELEFONE, TIPO_TELEFONE, NUMERO, ID_CLIENTE) VALUES(NULL,'PESSOAL','78989765',3);
INSERT INTO TELEFONE(IDTELEFONE, TIPO_TELEFONE, NUMERO, ID_CLIENTE) VALUES(NULL,'PESSOAL','99766676',3);
INSERT INTO TELEFONE(IDTELEFONE, TIPO_TELEFONE, NUMERO, ID_CLIENTE) VALUES(NULL,'COMERCIAL','66687899',1);
INSERT INTO TELEFONE(IDTELEFONE, TIPO_TELEFONE, NUMERO, ID_CLIENTE) VALUES(NULL,'RESIDENCIAL','89986668',5);
INSERT INTO TELEFONE(IDTELEFONE, TIPO_TELEFONE, NUMERO, ID_CLIENTE) VALUES(NULL,'PESSOAL','88687909',2);

/* ALTERANDO O NOME DE UMA COLUNA */
 ALTER TABLE ENDERECO CHANGE IDCLIENTE IDENDERECO INT(11);

 SELECT IDCLIENTE, NOME, SEXO, EMAIL, TIPO_TELEFONE, NUMERO /* projeção */
 FROM CLIENTE
 INNER JOIN TELEFONE
 ON IDCLIENTE = ID_CLIENTE
 WHERE SEXO = 'M';

 SELECT SEXO, COUNT(*) /* projeção */
 FROM CLIENTE
 WHERE SEXO = 'M';

 SELECT SEXO, COUNT(*) /* projeção */
 FROM CLIENTE 
 GROUP BY SEXO;

 SELECT TIPO_TELEFONE, COUNT(*)
 FROM TELEFONE
 GROUP BY TIPO_TELEFONE;

SELECT CLIENTE.IDCLIENTE, CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.MUNICIPIO, TELEFONE.TIPO_TELEFONE, TELEFONE.NUMERO
FROM CLIENTE
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE
INNER JOIN TELEFONE
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE;

SELECT C.IDCLIENTE, C.NOME, C.SEXO, E.BAIRRO, E.MUNICIPIO, T.TIPO_TELEFONE, T.NUMERO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T 
ON IDCLIENTE = T.ID_CLIENTE;


 /* projeção é tudo o que vejo na tela */
 /* seleção é um sub-cojunto do conjunto total de registros */

 /* RELATORIO GERAL DE TODOS OS CLIENTES */

 /* RELATORIO GERAL DE TODOS OS CLIENTES (TELEFONE E ENDERECO) */

  SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.MUNICIPIO, E.ESTADO, T.NUMERO, T.TIPO_TELEFONE
 FROM CLIENTE C
 INNER JOIN ENDERECO E
 ON IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
 ON IDCLIENTE = T.ID_CLIENTE
 ORDER BY IDCLIENTE ASC;

 +-----------+---------+------+-------------------+-------------+--------------------+------------+----------------+--------+----------+---------------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF         | RUA                | BAIRRO     | MUNICIPIO      | ESTADO | NUMERO   | TIPO_TELEFONE |
+-----------+---------+------+-------------------+-------------+--------------------+------------+----------------+--------+----------+---------------+
|         1 | JOAO    | M    | JOAOA@IG.COM      | 76567587887 | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     | 99667587 | RES           |
|         1 | JOAO    | M    | JOAOA@IG.COM      | 76567587887 | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     | 66687899 | COM           |
|         1 | JOAO    | M    | JOAOA@IG.COM      | 76567587887 | RUA CAPITAO HERMES | CENTRO     | RIO DE JANEIRO | RJ     | 87866896 | CEL           |
|         2 | CARLOS  | M    | CARLOSA@IG.COM    | 5464553466  | RUA ALFANDEGA      | ESTACIO    | RIO DE JANEIRO | RJ     | 54768899 | COM           |
|         2 | CARLOS  | M    | CARLOSA@IG.COM    | 5464553466  | RUA ALFANDEGA      | ESTACIO    | RIO DE JANEIRO | RJ     | 88687909 | CEL           |
|         3 | ANA     | F    | ANA@IG.COM        | 456545678   | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     | 78989765 | CEL           |
|         3 | ANA     | F    | ANA@IG.COM        | 456545678   | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     | 99766676 | CEL           |
|         5 | JORGE   | M    | JORGE@IG.COM      | 8756547688  | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     | 78458743 | CEL           |
|         5 | JORGE   | M    | JORGE@IG.COM      | 8756547688  | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     | 89986668 | RES           |
|         5 | JORGE   | M    | JORGE@IG.COM      | 8756547688  | RUA URUGUAIANA     | CENTRO     | VITORIA        | ES     | 56576876 | RES           |
|         8 | FLAVIO  | M    | FLAVIO@IG.COM     | 4657765     | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | 44522578 | COM           |
|         9 | ANDRE   | M    | ANDRE@GLOBO.COM   | 7687567     | RUA GUEDES         | CASCADURA  | B. HORIZONTE   | MG     | 68976565 | RES           |
|         9 | ANDRE   | M    | ANDRE@GLOBO.COM   | 7687567     | RUA GUEDES         | CASCADURA  | B. HORIZONTE   | MG     | 99656675 | CEL           |
|        11 | KARLA   | M    | KARLA@GMAIL.COM   | 545676778   | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | 33567765 | CEL           |
|        11 | KARLA   | M    | KARLA@GMAIL.COM   | 545676778   | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | 88668786 | CEL           |
|        11 | KARLA   | M    | KARLA@GMAIL.COM   | 545676778   | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | 55689654 | COM           |
|        12 | DANIELE | M    | DANIELE@GMAIL.COM | 43536789    | RUA NELSON MANDELA | COPACABANA | RIO DE JANEIRO | RJ     | 88687979 | COM           |
|        13 | LORENA  | M    | NULL              | 774557887   | RUA ARAUJO LIMA    | CENTRO     | VITORIA        | ES     | 88965676 | COM           |
|        15 | ANTONIO | F    | ANTONIO@IG.COM    | 12436767    | AV CAPITAO ANTUNES | CENTRO     | CURITIBA       | PR     | 89966809 | CEL           |
|        16 | ANTONIO | M    | ANTONIO@UOL.COM   | 3423565     | AV CARLOS BARROSO  | JARDINS    | SAO PAULO      | SP     | 88679978 | COM           |
|        17 | ELAINE  | M    | ELAINE@GLOBO.COM  | 32567763    | ALAMEDA SAMPAIO    | BOM RETIRO | CURITIBA       | PR     | 99655768 | CEL           |
|        18 | CARMEM  | M    | CARMEM@IG.COM     | 787832213   | RUA DA LAPA        | LAPA       | SAO PAULO      | SP     | 89955665 | RES           |
|        19 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942    | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     | 77455786 | RES           |
|        19 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942    | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     | 89766554 | RES           |
|        20 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256    | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | 77755785 | RES           |
|        20 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256    | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | 44522578 | COM           |
+-----------+---------+------+-------------------+-------------+--------------------+------------+----------------+--------+----------+---------------+


/* relatorio de mulheres */

SELECT * 
	FROM CLIENTE
 	WHERE IDCLIENTE = 7 
 	OR IDCLIENTE = 11
 	OR IDCLIENTE = 12
 	OR IDCLIENTE = 13
 	OR IDCLIENTE = 17
 	OR IDCLIENTE = 18;

 	SELECT * 
 	FROM CLIENTE
 	WHERE IDCLIENTE IN (7, 11, 12, 13, 17, 18);

+-----------+---------+------+-------------------+-----------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF       |
+-----------+---------+------+-------------------+-----------+
|         7 | PAULA   | M    | NULL              | 77437493  |
|        11 | KARLA   | M    | KARLA@GMAIL.COM   | 545676778 |
|        12 | DANIELE | M    | DANIELE@GMAIL.COM | 43536789  |
|        13 | LORENA  | M    | NULL              | 774557887 |
|        17 | ELAINE  | M    | ELAINE@GLOBO.COM  | 32567763  |
|        18 | CARMEM  | M    | CARMEM@IG.COM     | 787832213 |
+-----------+---------+------+-------------------+-----------+

 UPDATE CLIENTE
 	SET SEXO = 'F'
 	WHERE IDCLIENTE = 7 
 	OR IDCLIENTE = 11
 	OR IDCLIENTE = 12
 	OR IDCLIENTE = 13
 	OR IDCLIENTE = 17
 	OR IDCLIENTE = 18;

 UPDATE CLIENTE
 	SET SEXO = 'F'
 	WHERE IDCLIENTE IN (7, 11, 12, 13, 17, 18);
+-----------+---------+------+-------------------+-----------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF       |
+-----------+---------+------+-------------------+-----------+
|         7 | PAULA   | F    | NULL              | 77437493  |
|        11 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778 |
|        12 | DANIELE | F    | DANIELE@GMAIL.COM | 43536789  |
|        13 | LORENA  | F    | NULL              | 774557887 |
|        17 | ELAINE  | F    | ELAINE@GLOBO.COM  | 32567763  |
|        18 | CARMEM  | F    | CARMEM@IG.COM     | 787832213 |
+-----------+---------+------+-------------------+-----------+

 SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.MUNICIPIO, E.ESTADO, T.NUMERO, T.TIPO_TELEFONE
 FROM CLIENTE C
 INNER JOIN ENDERECO E
 ON IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T
 ON IDCLIENTE = T.ID_CLIENTE
 WHERE SEXO = 'F'
 ORDER BY IDCLIENTE ASC;

+-----------+---------+------+-------------------+-----------+--------------------+------------+----------------+--------+----------+---------------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | CPF       | RUA                | BAIRRO     | MUNICIPIO      | ESTADO | NUMERO   | TIPO_TELEFONE |
+-----------+---------+------+-------------------+-----------+--------------------+------------+----------------+--------+----------+---------------+
|         3 | ANA     | F    | ANA@IG.COM        | 456545678 | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     | 78989765 | CEL           |
|         3 | ANA     | F    | ANA@IG.COM        | 456545678 | RUA PRES VARGAS    | JARDINS    | SAO PAULO      | SP     | 99766676 | CEL           |
|        11 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778 | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | 33567765 | CEL           |
|        11 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778 | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | 88668786 | CEL           |
|        11 | KARLA   | F    | KARLA@GMAIL.COM   | 545676778 | RUA VISCONDESSA    | CENTRO     | RIO DE JANEIRO | RJ     | 55689654 | COM           |
|        12 | DANIELE | F    | DANIELE@GMAIL.COM | 43536789  | RUA NELSON MANDELA | COPACABANA | RIO DE JANEIRO | RJ     | 88687979 | COM           |
|        13 | LORENA  | F    | NULL              | 774557887 | RUA ARAUJO LIMA    | CENTRO     | VITORIA        | ES     | 88965676 | COM           |
|        17 | ELAINE  | F    | ELAINE@GLOBO.COM  | 32567763  | ALAMEDA SAMPAIO    | BOM RETIRO | CURITIBA       | PR     | 99655768 | CEL           |
|        18 | CARMEM  | F    | CARMEM@IG.COM     | 787832213 | RUA DA LAPA        | LAPA       | SAO PAULO      | SP     | 89955665 | RES           |
|        19 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942  | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     | 77455786 | RES           |
|        19 | ADRIANA | F    | ADRIANA@GMAIL.COM | 88556942  | RUA GERONIMO       | CENTRO     | RIO DE JANEIRO | RJ     | 89766554 | RES           |
|        20 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256  | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | 77755785 | RES           |
|        20 | JOICE   | F    | JOICE@GMAIL.COM   | 55412256  | RUA GOMES FREIRE   | CENTRO     | RIO DE JANEIRO | RJ     | 44522578 | COM           |
+-----------+---------+------+-------------------+-----------+--------------------+------------+----------------+--------+----------+---------------+

/* RELATORIO HOMENS */

 SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, C.CPF, E.RUA, E.BAIRRO, E.MUNICIPIO, E.ESTADO, T.NUMERO, T.TIPO_TELEFONE /* PROJEÇÃO */ 
 FROM CLIENTE C
 INNER JOIN ENDERECO E /* JUNÇÃO */ 
 ON IDCLIENTE = E.ID_CLIENTE
 INNER JOIN TELEFONE T /* JUNÇÃO */ 
 ON IDCLIENTE = T.ID_CLIENTE
 WHERE SEXO = 'M' /* SELEÇÃO */
 ORDER BY IDCLIENTE ASC;

+-----------+---------+------+-----------------+-------------+--------------------+-----------+----------------+--------+----------+---------------+
| IDCLIENTE | NOME    | SEXO | EMAIL           | CPF         | RUA                | BAIRRO    | MUNICIPIO      | ESTADO | NUMERO   | TIPO_TELEFONE |
+-----------+---------+------+-----------------+-------------+--------------------+-----------+----------------+--------+----------+---------------+
|         1 | JOAO    | M    | JOAOA@IG.COM    | 76567587887 | RUA CAPITAO HERMES | CENTRO    | RIO DE JANEIRO | RJ     | 87866896 | CEL           |
|         1 | JOAO    | M    | JOAOA@IG.COM    | 76567587887 | RUA CAPITAO HERMES | CENTRO    | RIO DE JANEIRO | RJ     | 99667587 | RES           |
|         1 | JOAO    | M    | JOAOA@IG.COM    | 76567587887 | RUA CAPITAO HERMES | CENTRO    | RIO DE JANEIRO | RJ     | 66687899 | COM           |
|         2 | CARLOS  | M    | CARLOSA@IG.COM  | 5464553466  | RUA ALFANDEGA      | ESTACIO   | RIO DE JANEIRO | RJ     | 54768899 | COM           |
|         2 | CARLOS  | M    | CARLOSA@IG.COM  | 5464553466  | RUA ALFANDEGA      | ESTACIO   | RIO DE JANEIRO | RJ     | 88687909 | CEL           |
|         5 | JORGE   | M    | JORGE@IG.COM    | 8756547688  | RUA URUGUAIANA     | CENTRO    | VITORIA        | ES     | 78458743 | CEL           |
|         5 | JORGE   | M    | JORGE@IG.COM    | 8756547688  | RUA URUGUAIANA     | CENTRO    | VITORIA        | ES     | 56576876 | RES           |
|         5 | JORGE   | M    | JORGE@IG.COM    | 8756547688  | RUA URUGUAIANA     | CENTRO    | VITORIA        | ES     | 89986668 | RES           |
|         8 | FLAVIO  | M    | FLAVIO@IG.COM   | 4657765     | RUA GOMES FREIRE   | CENTRO    | RIO DE JANEIRO | RJ     | 44522578 | COM           |
|         9 | ANDRE   | M    | ANDRE@GLOBO.COM | 7687567     | RUA GUEDES         | CASCADURA | B. HORIZONTE   | MG     | 68976565 | RES           |
|         9 | ANDRE   | M    | ANDRE@GLOBO.COM | 7687567     | RUA GUEDES         | CASCADURA | B. HORIZONTE   | MG     | 99656675 | CEL           |
|        15 | ANTONIO | M    | ANTONIO@IG.COM  | 12436767    | AV CAPITAO ANTUNES | CENTRO    | CURITIBA       | PR     | 89966809 | CEL           |
|        16 | ANTONIO | M    | ANTONIO@UOL.COM | 3423565     | AV CARLOS BARROSO  | JARDINS   | SAO PAULO      | SP     | 88679978 | COM           |
+-----------+---------+------+-----------------+-------------+--------------------+-----------+----------------+--------+----------+---------------+

SELECT SEXO, COUNT(*) FROM CLIENTE GROUP BY SEXO;

+------+----------+
| SEXO | COUNT(*) |
+------+----------+
| M    |        8 |
| F    |       12 |
+------+----------+

SELECT BAIRRO, COUNT(*) FROM CLIENTE INNER JOIN ENDERECO ON IDCLIENTE = ID_CLIENTE WHERE SEXO = 'F' AND MUNICIPIO = 'RIO DE JANEIRO' GROUP BY BAIRRO ORDER BY 2;

+------------+----------+
| BAIRRO     | COUNT(*) |
+------------+----------+
| COPACABANA |        1 |
| ESTACIO    |        1 |
| FLAMENGO   |        1 |
| CENTRO     |        3 |
+------------+----------+


SELECT TIPO_TELEFONE, COUNT(*) FROM CLIENTE INNER JOIN TELEFONE ON IDCLIENTE = ID_CLIENTE WHERE SEXO = 'F' GROUP BY TIPO_TELEFONE ORDER BY 2;

+---------------+----------+
| TIPO_TELEFONE | COUNT(*) |
+---------------+----------+
| COM           |        4 |
| RES           |        4 |
| CEL           |        5 |
+---------------+----------+

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, E.BAIRRO, E.MUNICIPIO, T.TIPO_TELEFONE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON IDCLIENTE = T.ID_CLIENTE
WHERE BAIRRO = 'CENTRO' AND MUNICIPIO = 'RIO DE JANEIRO' AND TIPO_TELEFONE != 'CEL' AND SEXO = 'F';

+-----------+---------+------+-------------------+--------+---------------+
| IDCLIENTE | NOME    | SEXO | EMAIL             | BAIRRO | TIPO_TELEFONE |
+-----------+---------+------+-------------------+--------+---------------+
|        11 | KARLA   | F    | KARLA@GMAIL.COM   | CENTRO | COM           |
|        19 | ADRIANA | F    | ADRIANA@GMAIL.COM | CENTRO | RES           |
|        19 | ADRIANA | F    | ADRIANA@GMAIL.COM | CENTRO | RES           |
|        20 | JOICE   | F    | JOICE@GMAIL.COM   | CENTRO | RES           |
|        20 | JOICE   | F    | JOICE@GMAIL.COM   | CENTRO | COM           |
+-----------+---------+------+-------------------+--------+---------------+

SELECT C.IDCLIENTE, C.NOME, C.SEXO, C.EMAIL, E.BAIRRO, E.MUNICIPIO, T.TIPO_TELEFONE
FROM CLIENTE C
INNER JOIN ENDERECO E
ON IDCLIENTE = E.ID_CLIENTE
INNER JOIN TELEFONE T
ON IDCLIENTE = T.ID_CLIENTE
ORDER BY 1;

/* PARA UMA CAMPANHA DE MARKETING, O SETOR SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
DOS CLIENTES QUE MORAM NO ESTADO DO RIO DE JANEIRO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME, C.EMAIL, T.NUMERO /* PROJEÇÃO */
FROM CLIENTE C
INNER JOIN TELEFONE T /* JUNÇÃO */
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E /* JUNÇÃO */
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE ESTADO = 'RJ' AND TIPO_TELEFONE = 'CEL'; /* SELEÇÃO */

+--------+-----------------+----------+
| NOME   | EMAIL           | NUMERO   |
+--------+-----------------+----------+
| JOAO   | JOAOA@IG.COM    | 87866896 |
| CARLOS | CARLOSA@IG.COM  | 88687909 |
| KARLA  | KARLA@GMAIL.COM | 33567765 |
| KARLA  | KARLA@GMAIL.COM | 88668786 |
+--------+-----------------+----------+

/* PARA UMA CAMPANHA DE PRODUTOS DE BELEZA, O COMERCIAL SOLICITOU UM
RELATÓRIO COM O NOME, EMAIL E TELEFONE CELULAR 
 DAS MULHERES QUE MORAM NO ESTADO DE SÃO PAULO 
VOCÊ TERÁ QUE PASSAR A QUERY PARA GERAR O RELATORIO PARA
O PROGRAMADOR */

SELECT C.NOME, C.EMAIL, T.NUMERO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE
WHERE SEXO = 'F' AND ESTADO = 'SP' AND TIPO_TELEFONE = 'CEL';

+------+------------+----------+
| NOME | EMAIL      | NUMERO   |
+------+------------+----------+
| ANA  | ANA@IG.COM | 78989765 |
| ANA  | ANA@IG.COM | 99766676 |
+------+------------+----------+

/* IFNULL */

SELECT C.NOME, C.EMAIL, E.ESTADO, T.NUMERO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

+---------+-------------------+--------+----------+
| NOME    | EMAIL             | ESTADO | NUMERO   |
+---------+-------------------+--------+----------+
| JORGE   | JORGE@IG.COM      | ES     | 78458743 |
| JORGE   | JORGE@IG.COM      | ES     | 56576876 |
| JOAO    | JOAOA@IG.COM      | RJ     | 87866896 |
| CARLOS  | CARLOSA@IG.COM    | RJ     | 54768899 |
| JOAO    | JOAOA@IG.COM      | RJ     | 99667587 |
| ANA     | ANA@IG.COM        | SP     | 78989765 |
| ANA     | ANA@IG.COM        | SP     | 99766676 |
| JOAO    | JOAOA@IG.COM      | RJ     | 66687899 |
| JORGE   | JORGE@IG.COM      | ES     | 89986668 |
| CARLOS  | CARLOSA@IG.COM    | RJ     | 88687909 |
| ANDRE   | ANDRE@GLOBO.COM   | MG     | 68976565 |
| ANDRE   | ANDRE@GLOBO.COM   | MG     | 99656675 |
| KARLA   | KARLA@GMAIL.COM   | RJ     | 33567765 |
| KARLA   | KARLA@GMAIL.COM   | RJ     | 88668786 |
| KARLA   | KARLA@GMAIL.COM   | RJ     | 55689654 |
| DANIELE | DANIELE@GMAIL.COM | RJ     | 88687979 |
| LORENA  | NULL              | ES     | 88965676 |
| ANTONIO | ANTONIO@IG.COM    | PR     | 89966809 |
| ANTONIO | ANTONIO@UOL.COM   | SP     | 88679978 |
| ELAINE  | ELAINE@GLOBO.COM  | PR     | 99655768 |
| CARMEM  | CARMEM@IG.COM     | SP     | 89955665 |
| ADRIANA | ADRIANA@GMAIL.COM | RJ     | 77455786 |
| ADRIANA | ADRIANA@GMAIL.COM | RJ     | 89766554 |
| JOICE   | JOICE@GMAIL.COM   | RJ     | 77755785 |
| JOICE   | JOICE@GMAIL.COM   | RJ     | 44522578 |
| FLAVIO  | FLAVIO@IG.COM     | RJ     | 44522578 |
+---------+-------------------+--------+----------+

SELECT C.NOME, IFNULL(C.EMAIL, 'NÃO RESGISTRADO') AS 'E-MAIL', E.ESTADO, T.NUMERO
FROM CLIENTE C
INNER JOIN TELEFONE T
ON C.IDCLIENTE = T.ID_CLIENTE
INNER JOIN ENDERECO E
ON C.IDCLIENTE = E.ID_CLIENTE;

+---------+-------------------+--------+----------+
| NOME    | E-MAIL            | ESTADO | NUMERO   |
+---------+-------------------+--------+----------+
| JORGE   | JORGE@IG.COM      | ES     | 78458743 |
| JORGE   | JORGE@IG.COM      | ES     | 56576876 |
| JOAO    | JOAOA@IG.COM      | RJ     | 87866896 |
| CARLOS  | CARLOSA@IG.COM    | RJ     | 54768899 |
| JOAO    | JOAOA@IG.COM      | RJ     | 99667587 |
| ANA     | ANA@IG.COM        | SP     | 78989765 |
| ANA     | ANA@IG.COM        | SP     | 99766676 |
| JOAO    | JOAOA@IG.COM      | RJ     | 66687899 |
| JORGE   | JORGE@IG.COM      | ES     | 89986668 |
| CARLOS  | CARLOSA@IG.COM    | RJ     | 88687909 |
| ANDRE   | ANDRE@GLOBO.COM   | MG     | 68976565 |
| ANDRE   | ANDRE@GLOBO.COM   | MG     | 99656675 |
| KARLA   | KARLA@GMAIL.COM   | RJ     | 33567765 |
| KARLA   | KARLA@GMAIL.COM   | RJ     | 88668786 |
| KARLA   | KARLA@GMAIL.COM   | RJ     | 55689654 |
| DANIELE | DANIELE@GMAIL.COM | RJ     | 88687979 |
| LORENA  | NÃO RESGISTRADO   | ES     | 88965676 |
| ANTONIO | ANTONIO@IG.COM    | PR     | 89966809 |
| ANTONIO | ANTONIO@UOL.COM   | SP     | 88679978 |
| ELAINE  | ELAINE@GLOBO.COM  | PR     | 99655768 |
| CARMEM  | CARMEM@IG.COM     | SP     | 89955665 |
| ADRIANA | ADRIANA@GMAIL.COM | RJ     | 77455786 |
| ADRIANA | ADRIANA@GMAIL.COM | RJ     | 89766554 |
| JOICE   | JOICE@GMAIL.COM   | RJ     | 77755785 |
| JOICE   | JOICE@GMAIL.COM   | RJ     | 44522578 |
| FLAVIO  | FLAVIO@IG.COM     | RJ     | 44522578 |
+---------+-------------------+--------+----------+

/* VIEW */

SELECT  C.NOME, C.SEXO, C.EMAIL, T.TIPO_TELEFONE, T.NUMERO, E.BAIRRO, E.MUNICIPIO, E.ESTADO
FROM CLIENTE C 
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE 
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE;

CREATE VIEW V_RELATORIO AS
	SELECT  C.NOME, C.SEXO, IFNULL(C.EMAIL,'********') AS 'E-MAIL', T.TIPO_TELEFONE, T.NUMERO, E.BAIRRO, E.MUNICIPIO, E.ESTADO
	FROM CLIENTE C 
	INNER JOIN TELEFONE T 
	ON C.IDCLIENTE = T.ID_CLIENTE 
	INNER JOIN ENDERECO E 
	ON C.IDCLIENTE = E.ID_CLIENTE;

	SELECT NOME, NUMERO, ESTADO
	FROM V_RELATORIO;

	/* UPDATE, INSERT E DELETE - DML */

INSERT INTO V_RELATORIO VALUES(
'ANDREIA','F','ANDREIA@UOL.COM.BR','CEL','873547864','CENTRO','VITORIA','ES'
);

ERROR 1394 (HY000): Can not insert into join view 'comercio.v_relatorio' without fields list
ERROR 1395 (HY000): Can not delete from join view 'comercio.v_relatorio'

DELETE FROM V_RELATORIO WHERE NOME = 'JORGE';

/* É PERMITIDO FAZER UPDATES EM VIEWS COM JOIN */

UPDATE V_RELATORIO SET NOME = 'JOSE' WHERE NOME = 'JORGE';

CREATE TABLE JOGADORES(
	IDJOGADOR INT,
	NOME VARCHAR(30),
	ESTADO CHAR(2)
);

INSERT INTO JOGADORES VALUES(1,'GUERRERO','RS');
INSERT INTO JOGADORES VALUES(2,'GABIGOL','RJ');
INSERT INTO JOGADORES VALUES(3,'GANSO','RJ');
INSERT INTO JOGADORES VALUES(4,'NENÊ', 'RJ');
INSERT INTO JOGADORES VALUES(5,'LOVE','SP');

CREATE VIEW V_JOGADORES AS
SELECT NOME, ESTADO
FROM JOGADORES;

SELECT * FROM V_JOGADORES;

DELETE FROM V_JOGADORES
WHERE NOME = 'GUERRERO';

INSERT INTO V_JOGADORES VALUES('GUERRERO','RS');

SELECT * FROM JOGADORES;

mysql> SELECT * FROM JOGADORES;
+-----------+----------+--------+
| IDJOGADOR | NOME     | ESTADO |
+-----------+----------+--------+
|         2 | GABIGOL  | RJ     |
|         3 | GANSO    | RJ     |
|         4 | NENÊ     | RJ     |
|         5 | LOVE     | SP     |
|      NULL | GUERRERO | RS     |
+-----------+----------+--------+

SELECT * FROM V_RELATORIO
WHERE SEXO = 'F';

lU&$3d8@7D0*

CREATE PROCEDURE CONTA(NUM1 INT, NUM2 INT)
	BEGIN
		SELECT NUM1 * NUM2 AS CONTA;
	END
$

DELIMITER ;

CALL CONTA(9, 8);

+-------+
| CONTA |
+-------+
|    72 |
+-------+

DROP PROCEDURE CONTA;

CREATE DATABASE MAFRA;

USE MAFRA;

CREATE TABLE CURSOS(
		IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(30) NOT NULL,
		HORAS INT(3),
		VALOR FLOAT(10,2)
);

DELIMITER $

CREATE PROCEDURE INSERIR(P_NOME VARCHAR(30), P_HORAS INT(3), P_VALOR FLOAT(10,2))
	BEGIN
		INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_VALOR);
	END
$

DELIMITER ;

CALL INSERIR('Banco de Dados', 60, 29.99);
CALL INSERIR('Microsoft BI', 10, 29.99);

DELIMITER $

CREATE PROCEDURE CONSULTA(P_IDCURSO INT)
	BEGIN
		SELECT NOME, HORAS, VALOR 
		FROM CURSOS
		WHERE IDCURSO = P_IDCURSO;
	END
$

DELIMITER ;

CREATE DATABASE LOJA;


CREATE TABLE VENDEDOR(
		IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
		NOME VARCHAR(30),
		SEXO CHAR(1),
		JANEIRO FLOAT(10,2),
		FEVEREIRO FLOAT(10,2),
		MARCO FLOAT(10,2)
	);

INSERT INTO VENDEDOR VALUES(NULL,'CARLOS','M',76234.78,88346.87,5756.90);
INSERT INTO VENDEDOR VALUES(NULL,'MARIA','F',5865.78,6768.87,4467.90);
INSERT INTO VENDEDOR VALUES(NULL,'ANTONIO','M',78769.78,6685.87,6664.90);
INSERT INTO VENDEDOR VALUES(NULL,'CLARA','F',5779.78,446886.87,8965.90);
INSERT INTO VENDEDOR VALUES(NULL,'ANDERSON','M',676545.78,77544.87,578665.90);
INSERT INTO VENDEDOR VALUES(NULL,'IVONE','F',57789.78,44774.87,68665.90);
INSERT INTO VENDEDOR VALUES(NULL,'JOAO','M',4785.78,66478.87,6887.90);
INSERT INTO VENDEDOR VALUES(NULL,'CELIA','F',89667.78,57654.87,5755.90);

+-------------+----------+------+-----------+-----------+-----------+
| IDVENDENDOR | NOME     | SEXO | JANEIRO   | FEVEREIRO | MARCO     |
+-------------+----------+------+-----------+-----------+-----------+
|           1 | CARLOS   | M    |  76234.78 |  88346.87 |   5756.90 |
|           2 | MARIA    | F    |   5865.78 |   6768.87 |   4467.90 |
|           3 | ANTONIO  | M    |  78769.78 |   6685.87 |   6664.90 |
|           4 | CLARA    | F    |   5779.78 | 446886.88 |   8965.90 |
|           5 | ANDERSON | M    | 676545.75 |  77544.87 | 578665.88 |
|           6 | IVONE    | F    |  57789.78 |  44774.87 |  68665.90 |
|           7 | JOAO     | M    |   4785.78 |  66478.87 |   6887.90 |
|           8 | CELIA    | F    |  89667.78 |  57654.87 |   5755.90 |
+-------------+----------+------+-----------+-----------+-----------+

/* SELECIONA O MAIOR VALOR DA COLUNA */

SELECT MAX(FEVEREIRO) AS MAIOR_VAL FROM VENDEDOR;

+-----------+
| MAIOR_VAL |
+-----------+
| 446886.88 |
+-----------+

/* SELECIONA O MENOR VALOR DA COLUNA */ 

SELECT MIN(FEVEREIRO) AS MAIOR_VAL FROM VENDEDOR;

+-----------+
| MAIOR_VAL |
+-----------+
|   6685.87 |
+-----------+

DELIMITER $

CREATE PROCEDURE PROC_MAX(IN P_MES VARCHAR(20))
	BEGIN
    	SET @sql = CONCAT('SELECT MAX(', P_MES, ') AS MAIOR_VAL FROM VENDEDOR');
    	PREPARE stmt FROM @sql;
    	EXECUTE stmt;
    	DEALLOCATE PREPARE stmt;
	END
$

/* CÁLCULA A MÉDIA */

SELECT AVG(FEVEREIRO) AS MEDIA_FEV FROM VENDEDOR;

/* TRUNCATE MANIPULA A FORMATAÇÃO DE VALORES
	TRUNCATE(100.99999, 2)
	100.99
 */

SELECT 	MAX(JANEIRO) AS MAXIMO_JAN,
		MIN(JANEIRO) AS MININO_JAN,
		TRUNCATE(AVG(JANEIRO),2) AS MEDIA_JAN
FROM VENDEDOR;

+------------+------------+-----------+
| MAXIMO_JAN | MININO_JAN | MEDIA_JAN |
+------------+------------+-----------+
|  676545.75 |    4785.78 | 124429.90 |
+------------+------------+-----------+

SELECT 	SUM(JANEIRO) AS TOTAL_JAN,
		SUM(FEVEREIRO) AS TOTAL_FEV,
		SUM(MARCO) AS TOTAL_MAR
FROM VENDEDOR;

+-----------+-----------+-----------+
| TOTAL_JAN | TOTAL_FEV | TOTAL_MAR |
+-----------+-----------+-----------+
| 995439.21 | 795141.96 | 685831.17 |
+-----------+-----------+-----------+

SELECT SEXO, SUM(JANEIRO) AS TOTAL_JAN
FROM VENDEDOR
GROUP BY SEXO;

ALTER TABLE VENDEDOR
MODIFY IDVENDEDOR INT AUTO_INCREMENT;

SELECT NOME, MARCO FROM VENDEDOR WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDOR);

+-------+---------+
| NOME  | MARCO   |
+-------+---------+
| MARIA | 4467.90 |
+-------+---------+

SELECT NOME, MARCO FROM VENDEDOR WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDOR);

+----------+-----------+
| NOME     | MARCO     |
+----------+-----------+
| ANDERSON | 578665.88 |
+----------+-----------+

SELECT NOME, MARCO FROM VENDEDOR WHERE MARCO >= (SELECT AVG(FEVEREIRO) FROM VENDEDOR);